const {
  mock
} = require('node:test')

/**
 *  Capture and return all stdout generated by cb:
 * **/
const captureStdout = (cb) => {
  const buffer = []

  // Intercept stdout writes:
  mock.method(process.stdout, 'write', (s) => {
    buffer.push(s)
  })

  cb()

  // Restore stdout:
  mock.reset()

  return buffer
}

/**
 *  Temporarily set some env vars for the execution of cb
 * **/
const setEnv = (env, cb) => {
  // Snapshot former values:
  const originalValues = Object.keys(env)
    .reduce((h, key) => ({ ...h, [key]: process.env[key] }), {})

  // Set new values:
  Object.entries(env)
    .filter(([key, value]) => value)
    .forEach(([key, value]) => {
      process.env[key] = value
    })

  cb()

  // Restore prior state:
  Object.entries(originalValues).forEach(([key, value]) => {
    if (!value) {
      delete process.env[key]
    } else {
      process.env[key] = value
    }
  })
}

module.exports = {
  captureStdout,
  setEnv
}
